/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Usuário
 */
public class NewJFrameCalculadora extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrameCalculadora
     */
    public NewJFrameCalculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel14 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton16 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButtonLimpar = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButtonDivisão = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButtonMultiplicação = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButtonSubtraçao = new javax.swing.JButton();
        jButtonSomar = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButtonResultado = new javax.swing.JButton();

        jLabel14.setText("jLabel14");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora Java");

        jLabel1.setBackground(new java.awt.Color(51, 255, 255));
        jLabel1.setFont(new java.awt.Font("Humnst777 Lt BT", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 255, 255));

        jPanel1.setLayout(new java.awt.GridLayout(0, 4, 4, 6));

        jButton16.setFont(new java.awt.Font("Humnst777 Lt BT", 1, 18)); // NOI18N
        jButton16.setText("%");
        jButton16.setPreferredSize(new java.awt.Dimension(30, 30));
        jPanel1.add(jButton16);

        jButton2.setFont(new java.awt.Font("Humnst777 Lt BT", 1, 18)); // NOI18N
        jButton2.setText("CE");
        jButton2.setPreferredSize(new java.awt.Dimension(30, 30));
        jPanel1.add(jButton2);

        jButton1.setFont(new java.awt.Font("Humnst777 Lt BT", 1, 18)); // NOI18N
        jButton1.setText("C");
        jButton1.setPreferredSize(new java.awt.Dimension(30, 30));
        jPanel1.add(jButton1);

        jButtonLimpar.setFont(new java.awt.Font("Humnst777 Lt BT", 1, 18)); // NOI18N
        jButtonLimpar.setText("EX");
        jButtonLimpar.setPreferredSize(new java.awt.Dimension(30, 30));
        jPanel1.add(jButtonLimpar);

        jButton14.setText("jButton14");
        jPanel1.add(jButton14);

        jButton3.setText("jButton3");
        jPanel1.add(jButton3);

        jButton6.setText("jButton6");
        jPanel1.add(jButton6);

        jButtonDivisão.setFont(new java.awt.Font("Humnst777 Lt BT", 1, 18)); // NOI18N
        jButtonDivisão.setText("/");
        jButtonDivisão.setPreferredSize(new java.awt.Dimension(30, 30));
        jPanel1.add(jButtonDivisão);

        jButton9.setFont(new java.awt.Font("Humnst777 Lt BT", 1, 18)); // NOI18N
        jButton9.setText("7");
        jButton9.setPreferredSize(new java.awt.Dimension(30, 30));
        jPanel1.add(jButton9);

        jButton5.setFont(new java.awt.Font("Humnst777 Lt BT", 1, 18)); // NOI18N
        jButton5.setText("8");
        jButton5.setPreferredSize(new java.awt.Dimension(30, 30));
        jPanel1.add(jButton5);

        jButton4.setFont(new java.awt.Font("Humnst777 Lt BT", 1, 18)); // NOI18N
        jButton4.setText("9");
        jButton4.setPreferredSize(new java.awt.Dimension(30, 30));
        jPanel1.add(jButton4);

        jButton13.setFont(new java.awt.Font("Humnst777 Lt BT", 1, 18)); // NOI18N
        jButton13.setText("X");
        jButton13.setPreferredSize(new java.awt.Dimension(30, 30));
        jPanel1.add(jButton13);

        jButtonMultiplicação.setFont(new java.awt.Font("Humnst777 Lt BT", 1, 18)); // NOI18N
        jButtonMultiplicação.setText("4");
        jButtonMultiplicação.setPreferredSize(new java.awt.Dimension(30, 30));
        jPanel1.add(jButtonMultiplicação);

        jButton7.setFont(new java.awt.Font("Humnst777 Lt BT", 1, 18)); // NOI18N
        jButton7.setText("5");
        jButton7.setPreferredSize(new java.awt.Dimension(30, 30));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);

        jButton8.setFont(new java.awt.Font("Humnst777 Lt BT", 1, 18)); // NOI18N
        jButton8.setText("6");
        jButton8.setPreferredSize(new java.awt.Dimension(30, 30));
        jPanel1.add(jButton8);

        jButton12.setFont(new java.awt.Font("Humnst777 Lt BT", 1, 18)); // NOI18N
        jButton12.setText("-");
        jButton12.setPreferredSize(new java.awt.Dimension(30, 30));
        jPanel1.add(jButton12);

        jButton10.setFont(new java.awt.Font("Humnst777 Lt BT", 1, 18)); // NOI18N
        jButton10.setText("1");
        jButton10.setPreferredSize(new java.awt.Dimension(30, 30));
        jPanel1.add(jButton10);

        jButton11.setFont(new java.awt.Font("Humnst777 Lt BT", 1, 18)); // NOI18N
        jButton11.setText("2");
        jButton11.setPreferredSize(new java.awt.Dimension(30, 30));
        jPanel1.add(jButton11);

        jButtonSubtraçao.setFont(new java.awt.Font("Humnst777 Lt BT", 1, 18)); // NOI18N
        jButtonSubtraçao.setText("3");
        jButtonSubtraçao.setPreferredSize(new java.awt.Dimension(30, 30));
        jPanel1.add(jButtonSubtraçao);

        jButtonSomar.setFont(new java.awt.Font("Humnst777 Lt BT", 1, 18)); // NOI18N
        jButtonSomar.setText("+");
        jButtonSomar.setPreferredSize(new java.awt.Dimension(30, 30));
        jPanel1.add(jButtonSomar);

        jButton15.setFont(new java.awt.Font("Humnst777 Lt BT", 1, 18)); // NOI18N
        jButton15.setText("+/-");
        jPanel1.add(jButton15);

        jButton18.setFont(new java.awt.Font("Humnst777 Lt BT", 1, 18)); // NOI18N
        jButton18.setText("0");
        jButton18.setPreferredSize(new java.awt.Dimension(30, 30));
        jPanel1.add(jButton18);

        jButton19.setFont(new java.awt.Font("Humnst777 Lt BT", 1, 18)); // NOI18N
        jButton19.setText(",");
        jButton19.setPreferredSize(new java.awt.Dimension(30, 30));
        jPanel1.add(jButton19);

        jButtonResultado.setFont(new java.awt.Font("Humnst777 Lt BT", 1, 18)); // NOI18N
        jButtonResultado.setText("=");
        jButtonResultado.setPreferredSize(new java.awt.Dimension(30, 30));
        jPanel1.add(jButtonResultado);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrameCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrameCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrameCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrameCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrameCalculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonDivisão;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JButton jButtonMultiplicação;
    private javax.swing.JButton jButtonResultado;
    private javax.swing.JButton jButtonSomar;
    private javax.swing.JButton jButtonSubtraçao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
